> vrlggscraper@1.0.3 start > node src/.
node:internal/modules/cjs/loader:1247
  throw err;
  ^

Error: Cannot find module './versions/v1/routes/matchesr'
Require stack:
- C:\Users\lamon\OneDrive\Documentos\Esports\vlresports\src\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function._load (node:internal/modules/cjs/loader:1070:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\lamon\OneDrive\Documentos\Esports\vlresports\src\index.js:28:28)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lamon\\OneDrive\\Documentos\\Esports\\vlresports\\src\\index.js'
  ]
}

Node.js v22.13.0